### ISSUE TITLE
Make this repo easier to contribute to

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#1512]
This issue should be a place where we can put pieces that make this repository difficult to contribute to. I'll start.

- Extra long output for `build` errors. [Here is an example.](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/6711/workflows/fca0c433-dd66-4d8a-acb1-0d7014ac4a72/jobs/33418) It's not clear to me which ones are real and which are not; clearly some are not since they are in unrelated queries
- Failures of CI that don't arise when I run `pytest`. It really inhibits momentum when you push what you think is a good change, only to have multiple CI steps fail (e.g. airflow dag generation) that did not even run locally. Local testing should include all of those

**Comment by jklukas** [comment]
Permissions are an issue here that definitely complicate the issue. Some CI steps rely on GCP credentials and others rely on the dry run service. It may be difficult to get airflow dag generation running in the same way locally as in CI due to this for example. So perhaps a first step would be documenting those dependencies to see if we can develop a coherent approach to what is and is not able to run locally.

We also have the confounding issue that when adding new tables it is often not possible to get CI to pass without being a data platform engineer with access to actually create the table.

We also do not document in this repo what the workflow is like for PRs from forks. Some CI tasks will not be able to run at all in that case.

**Comment by fbertsch** [comment]
Good point, dryruns are really limiting us. They cause random test failures, airflow dag generation is reliant on them, and yet CI still fails if you haven't properly updated DAGs.

**Comment by wlach** [comment]
There's a larger set of issues here that we should probably tackle individually. I filed #1642 and #1643 for the issues discussed above and created a `usability` label we can apply to issues in this family (there were a few others filed by @sunahsuh in this category last year, and I have a few more in my backlog). Closing this with @fbertsch's permission.
