### ISSUE TITLE
Support schema files in query directories

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1539]
The proposal here is motivated by the [Daily Per-Client Aggregations](https://docs.google.com/document/d/1Lml-hWiqhvUazjn_-sDF6TUvwAEA3jMG3LJbyIC7fEc/edit#) workstream which seeks to allow us to more confidently deploy new fields to clients_daily, etc.

This repository already contains some BQ schemas as `schema.yaml` files in tests and in generated GLAM queries. We could build in direct support for schema files as part of the bqetl execution machinery with the following benefits:

- Allows a natural place to insert field descriptions, which we currently lack for derived tables and views
- We could detect schema changes as part of dry runs, providing a foothold to solve the "field addition surprise" failure mode for clients_daily and clients_last_seen

We would need to provide the following new affordances:

- A new bqetl invocation to allow easily pulling down the schema of an existing table or view, writing out a `schema.yaml` file in the appropriate directory (as a way to opt a query into this new functionality)
- A new bqetl invocation apply `schema.yaml` to update the schema of a table
- In the dryrun cloud function, return the schema of the result as part of the output; see [JobStatistics2.schema](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobstatistics2); this should be present in JS as `job[0].metadata.statistics.schema` or in python as `job._job_statistics()['schema']`
- In the bqetl dryrun machinery, if `schema.yaml` exists, check it against the returned schema from the dryrun service; fail the dry run if they do not match (we'll probably need some logic to ensure stable ordering)

If we had the above, we could produce `schema.yaml` files for clients_daily, clients_last_seen, and clients_first_seen. When we add a new field to `clients_daily`, this would cause dry run to fail with a mismatch showing the mismatch with `schema.yaml`; the developer would then be sure to add that field to `schema.yaml` as part of the PR, including a description for the field, and then run `bqetl query schema apply` to push that new field to shared-prod. This will now cause clients_last_seen and clients_first_seen to fail dry runs due to the new field in clients_daily, prompting the developer to apply the same schema evolution steps to clients_last_seen.

We would document the workflow for evolving clients_daily/clients_last_seen, and hopefully the initially dryrun failure for clients_daily would jog the developer's memory to look up the docs before proceeding with a sequence of ad hoc schema updates and new dry run failures.

Ideally, we would be able to catch all of this within dryruns without having to go ahead and apply the schema updates in shared-prod, but I think that would require some fundamental rethinking of how execution works here. I am definitely open to feedback that the proposed changes above are too much complexity and risk, and that we should delay this to a more holistic refactoring.

**Comment by whd** [comment]
I'm cautiously optimistic that we can introduce changes like this in preparation for a more holistic refactoring later that incorporates smaller pieces. I think we're going to want schema files eventually for all the things in any case for deployment unification, and this seems like a key step toward that. I don't have much to say on the complexity of the bq-etl workflow this introduces but even if we fundamentally rethink the way the machinery works I doubt it will not involve schemas.

**Comment by fbertsch** [comment]
It looks to me like this takes precedence over the proposal of allowing schema additions to fields. Instead of default allowing it across the board, this would enable a straightforward way to describe and allow field additions. Does that sound right, @jklukas?

One note I have is that for me, dryruns almost always fail. Relying on them succeeding would be a huge benefit here. We should, alongside this, work on only dryrunning queries that were altered from `master`. If a query was not altered in that PR, then it doesn't run.

If we can get this mechanism working, we could add local tests that run the dryruns compared to `origin/master`. Then developers could see this fail while running tests instead of during CI.

**Comment by jklukas** [comment]
> Instead of default allowing it across the board, this would enable a straightforward way to describe and allow field additions.

Correct, if we go this direction, we'd likely have no need to allow schema updates in queries, since the correct schema would already be applied via `bq update` beforehand.

> We should, alongside this, work on only dryrunning queries that were altered from master. If a query was not altered in that PR, then it doesn't run.

I don't see a clear path to doing this safely. In the example of updating the clients_daily schema while forgetting to update the clients_last_seen schema, a git-based approach would indicate clients_last_seen hasn't changed and doesn't need to be dry run, but in practice clients_last_seen is no longer valid, because its dependency changed.

> One note I have is that for me, dryruns almost always fail

That's definitely worth breaking off to its own issue to see if we can understand the root causes and see if there are additional approaches we can consider.

**Comment by scholtzan** [comment]
When testing for schema incompatibilites, would it be possible to deploy all schemas defined in `schema.yaml` files to the `bigquery-etl-integration-test` project and then dry run against these tables? Queries would get updated automatically in the CI step to reference these tables instead of the corresponding shared-prod ones. 
This would avoid having to manually add fields to shared-prod tables and potentially prevent errors like adding fields to tables before changes have been reviewed to make the CI check succeed and accidentally adding fields with typos that could have been caught in a review.

It would be ideal to automatically apply `schema.yaml` on deploy. But I guess there might be problems with permissions that need to be worked out for this step though.

**Comment by sunahsuh** [comment]
> If we had the above, we could produce schema.yaml files for clients_daily, clients_last_seen, and clients_first_seen. When we add a new field to clients_daily, this would cause dry run to fail with a mismatch showing the mismatch with schema.yaml; the developer would then be sure to add that field to schema.yaml as part of the PR, including a description for the field, and then run bqetl query schema apply to push that new field to shared-prod.

Is there any way to inherit portions of the schema from `clients_daily`? While I understand the impetus for making schema evolution explicit, making the contributor add these columns downstream when _those queries_ implicitly inherit from `clients_daily` adds a barrier that's, imo, still opaque to the contributor (e.g. attitudes_daily_v1 also inherits from clients_daily and most users don't even know that table exists.)

> It looks to me like this takes precedence over the proposal of allowing schema additions to fields. Instead of default allowing it across the board, this would enable a straightforward way to describe and allow field additions.

I'm concerned that manually adding fields to the schema when the query can do that adds friction to contribution for this repo. I think there's a much bigger chance that the user makes a mistake when _manually_ specifying the schema (that is, creating a mismatched schema) than if we allow schema additions via the query.

The ability to add description metadata is a compelling pro, imo, but unless that's part of the initial implementation I'm not sure there's much in the way of benefit for anyone over allowing schema additions (with the exception of `clients_daily` and downstream, where this solves a real problem.)

**Comment by jklukas** [comment]
> When testing for schema incompatibilites, would it be possible to deploy all schemas defined in schema.yaml files to the bigquery-etl-integration-test project and then dry run against these tables? Queries would get updated automatically in the CI step to reference these tables instead of the corresponding shared-prod ones.
> This would avoid having to manually add fields to shared-prod tables and potentially prevent errors like adding fields to tables before changes have been reviewed to make the CI check succeed and accidentally adding fields with typos that could have been caught in a review.

This does feel like a logical evolution of this project's testing capabilities, and it would open up a lot of opportunities. That said, I think trying to inspect existing queries and change table references to refer to a test project would be difficult and could lead to surprising behavior for the user. I expect that achieving this would mean we need to lean into query templating, where all queries are expressed as templates and we have special ways of expressing table references so that they can be reliably filled in either for testing or for production.

> Is there any way to inherit portions of the schema from clients_daily?

Not automatically, but we could certainly tooling to support this. @fbertsch is introducing some more structure around query generation for the events_daily work which includes enforcing that CI runs the events_daily generation and fails if it doesn't match what's checked in. I could imagine we add some code for clients_daily schema propagation there, so that when we change the clients_daily schema it ensures that new fields are merged into all the downstream tables dependent on that schema.

Taking a step back, let's imagine someone relatively new to the codebase modifies the clients_daily query, adding a new field. They then run tests, and the dry run detects a mismatch between the schema and the query, emitting an error message that describes this problem and suggests a `bqetl` invocation to use to update the schema file to match the query logic. The developer follows that instruction, then reruns tests and gets a new error message about clients_last_seen not matching the clients_daily schema and suggesting a different `bqetl` invocation to use to propagate the clients_daily schema. After that is run, we have succeeding tests and the codebase is in state where Airflow will be able to successfully apply new schemas and run queries.

**Comment by sunahsuh** [comment]
> Taking a step back, let's imagine someone relatively new to the codebase modifies the clients_daily query, adding a new field. They then run tests, and the dry run detects a mismatch between the schema and the query, emitting an error message that describes this problem and suggests a bqetl invocation to use to update the schema file to match the query logic. The developer follows that instruction, then reruns tests and gets a new error message about clients_last_seen not matching the clients_daily schema and suggesting a different bqetl invocation to use to propagate the clients_daily schema. After that is run, we have succeeding tests and the codebase is in state where Airflow will be able to successfully apply new schemas and run queries.

Picking this back up, especially in light of the renewed focus on making contributions to the repo out of the working group – I'd like to push back a bit on the use of tests as the _primary_ enforcement mechanism for expectations, especially when a failing result is a surprise to the developer (and to clarify, this isn't to say that we shouldn't enforce these standards automatically – just that we should think carefully about limiting surprise). I think as a contributor who's not entirely familiar with the details of the codebase, a loop of fail-fail-fail-pass on CI where CI is the _main_ discovery mechanism for contribution requirements doesn't inspire a ton of confidence that you've actually done things correctly and rather, imo, leaves an impression of brittleness.

I think in my ideal world where we have infinite resources to invest in tooling, etc, we'd have a single command that we ask contributors to run before commit that:
- formats sql
- generates dags
- autogenerates schema files based on the bq query, including down the chain because we've made inheritance relationships explicit

We live in the real world and we don't have infinite resources – but I think noodling on how to reduce surprise is important and that changes that increase the level of surprise will make this repo less accessible.

**Comment by jklukas** [comment]
> noodling on how to reduce surprise is important and that changes that increase the level of surprise will make this repo less accessible

Thank you for this assessment. You're definitely right that the workflows proposed here so far are not sufficiently friendly to justify the safety gains. I do suspect we'll eventually realize benefits from maintaining schemas for derived tables, but we need a better path there, likely as part of an overall rethinking of how the repo works.

**Comment by jklukas** [comment]
See https://github.com/mozilla/bigquery-etl/pull/1718 for a proposed alternative to schema files in query directories. Instead, it defines a `bqetl query schema` command that does a dry-run of the `init.sql`, which includes the updated schema in its response. Running that command over the clients_daily ETL chain would be a programmatic way to apply schema updates without any new metadata needed.

**Comment by jklukas** [comment]
This is supported now. See #1749
