### ISSUE TITLE
query_file_path in DAGs not recognized by bigquery_etl_query

### ISSUE THREAD

**Issue by Ben-Wu** [mozilla/bigquery-etl#1542]
#1536 changed the `sql_file_path` to `query_file_path` which is causing the argument to not be used because the `bigquery_etl_query` function in airflow still expects `sql_file_path`.

The error I'm seeing is:
```
b"FileNotFoundError: [Errno 2] No such file or directory: 'sql/moz-fx-data-marketing-prod/ga_derived/None/query.sql'\n"
```
[link](https://workflow.telemetry.mozilla.org/log?task_id=ga_derived__blogs_empty_check__v1&dag_id=bqetl_google_analytics_derived&execution_date=2020-11-09T23%3A00%3A00%2B00%3A00)

I think main summary will be affected by this.

cc @scholtzan @jklukas

**Comment by scholtzan** [comment]
Fixed in https://github.com/mozilla/bigquery-etl/pull/1543.

I think we'll still be running into errors tonight though. The new Airflow update changed the retry behaviour of failed pods: https://github.com/apache/airflow/issues/12111 So even if we clear the failed Airflow task it won't pick up the updated container with the fix. One solution would be to manually delete the affected pods and then rerun them. Unfortunately, I don't have the permissions to do that

**Comment by scholtzan** [comment]
The pod got deleted and it is now running successfully.

**Comment by jklukas** [comment]
Indeed it looks like we have several tasks that failed last night due to reattaching to failed pods.

https://workflow.telemetry.mozilla.org/log?task_id=account_ecosystem_derived__ecosystem_user_id_lookup__v1&dag_id=bqetl_account_ecosystem&execution_date=2020-11-10T02%3A00%3A00%2B00%3A00
https://workflow.telemetry.mozilla.org/log?task_id=telemetry_derived__error_aggregates__v1&dag_id=bqetl_error_aggregates&execution_date=2020-11-09T23%3A48%3A08.661094%2B00%3A00
https://workflow.telemetry.mozilla.org/log?task_id=ga_derived__blogs_empty_check__v1&dag_id=bqetl_google_analytics_derived&execution_date=2020-11-09T23%3A00%3A00%2B00%3A00
