### ISSUE TITLE
Add init.sql files to dry run

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/bigquery-etl#1620]
My assumption was that `init.sql` files were dry-run like the `query.sql` and `view.sql` files but I just had an initialization query fail because it contained 5 clustering columns instead of 4. If we can catch this in CI that seems worthwhile.

**Comment by jklukas** [comment]
It should be the case (at least it has in the past) that `init.sql` files are subject to dry run, although we often end up adding them to exemption list because vanilla `CREATE TABLE` will fail on a table that already exists (we can use `CREATE TABLE IF NOT EXISTS` to sidestep this, though). What's the particular file that was failing? Perhaps it caught a glob expression?

**Comment by sunahsuh** [comment]
`sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/init.sql` is the file

Sure looks like we're only looking at views and queries to me: https://github.com/mozilla/bigquery-etl/blob/master/bigquery_etl/dryrun.py#L222

**Comment by jklukas** [comment]
Looks like this behavior changed in October as part of https://github.com/mozilla/bigquery-etl/pull/1353 

@scholtzan - Was this exemption of `init.sql` intentional?

Assuming we choose to allow `init.sql` files for dry run again, I would suggest that we document a convention of using `CREATE TABLE IF NOT EXISTS` in those files, update existing `init.sql` files to that style, and remove the existing SKIP entries for `init.sql` files.
