### ISSUE TITLE
Implement `generated-sql` branch to capture missing datasets

### ISSUE THREAD

**Issue by Iinh** [mozilla/bigquery-etl#1742]
Right now not every dataset is checked in to `sql/`, which results to missing content in the generated docs that I'm working on in #1735. 

[@jklukas's comment:](https://github.com/mozilla/bigquery-etl/pull/1735#issuecomment-771180105)

> For Glean applications, we have some machinery that generates and runs queries that don't appear under the sql folder that's checked in, so they don't appear in these generated docs. For example, there's a user-facing org_mozilla_ios_firefox dataset that's missing here.
> 
> This could be more motivation for maintaining a generated-sql branch (see #1110 (comment)), but shouldn't block this effort. This could be another future improvement.
>

**Comment by jklukas** [comment]
I totally forgot the most basic case of generated views: views into stable ping tables in the `_stable` datasets. These are mostly generated via machinery in `bigquery_etl` as well and should be included in the `generated-sql` branch.

**Comment by jklukas** [comment]
I'm taking a look into this right now.

**Comment by jklukas** [comment]
I have a `gensql` branch with the requisite `git` logic, but looks like permissions are an issue. Currently, generating views requires hitting BQ to list stable tables, and we don't provision creds to this repo that allow that. It should be feasible to recast that logic to rely on the `generated-schemas` branch of mozilla-pipeline-schemas instead.

**Comment by jklukas** [comment]
> It should be feasible to recast that logic to rely on the generated-schemas branch of mozilla-pipeline-schemas instead.

This is indeed feasible and I've put together a basic implementation of it, but it brings up an additional sequencing problem. When we list actual tables in BQ, we can be sure they exist. When we list tables from `generated-schemas`, there is the possibility of a new doctype being included which has not yet gone through ops logic and been created in BQ.

We have previously discussed the possibility of something like a `generated-schemas-prod` branch on m-p-s that we'd publish to as part of ops logic, after all BQ resources have been updated/created. I think the most sane approach here would be to rely on such a branch.

As a stop-gap, we could have the view generation logic include a dry run, and skip any views that fail dry run due to underlying tables not existing. That is a bit less clean and brings up the possibility of hiding legitimate problems that should result in a failure.

@whd - Do you have an opinion here? Would it be difficult to implement publishing to a `generated-schemas-prod` as part of ops logic?

**Comment by jklukas** [comment]
Spoke with @whd on Zoom. He have an okay to the path of "have the view generation logic include a dry run, and skip any views that fail dry run due to underlying tables not existing" so I'll proceed with that.
