### ISSUE TITLE
`bqetl query create` should have some default scheduling setup in `metadata.yaml`

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#3650]
Right now, when you run `bqetl query create`, you don't actually get any scheduling.

It would be helpful to default to a standard scheduling location, just to help ensure people's things actually get scheduled.

**Comment by scholtzan** [comment]
cc @curtismorales @wwyc  as reviewers

**Comment by lucia-vargas-a** [comment]
I'm creating DAG `bqetl_default` as a default location to schedule queries.

**Comment by lucia-vargas-a** [comment]
I see two options and some trade-offs. Which one would you recommend, or do you have something else in mind :[scholtzan](https://github.com/scholtzan)], [fbertsch](https://github.com/fbertsch)?

**Option 1. Add scheduler to [`./bqetl query create`](https://github.com/mozilla/bigquery-etl/blob/1c3ba13b4048d98d3da690b1a89710ab8c022f75/bigquery_etl/cli/query.py#L112):**
- Create (once) a default DAG for queries e.g. `bqetl_default` and schedule it to run at a specific time.
- Add an input parameter e.g. `--default-schedule` to command `./bqetl query create`.
- When the input parameter `--default_schedule` is selected, run the function schedule() inside `./bqetl query create ` to schedule this query in DAG `bqetl_default`. This step updates the DAG and the query metadata.

**Trade-Offs:**
- Using the `--default-schedule` option makes the process easier, therefore it may be used often and result in several queries scheduled in the default DAG instead of maintaining organized DAGs running related tasks.
- If a dependency is scheduled after the `default_dag` schedule, the corresponding task will not be updated with the latest data. This can be minimized if we use a later time for DAG `default_dag` e.g. 13h PDT, or the developer uses a custom DAG that fits the required schedule.
- If developers wants to change the scheduling from the `default_dag` to another DAG, they will need to do this manually.
- For the queries to actually get scheduled, developers need to actively include the `--default_scheduling` option. The advantage is that there is awareness of where and when the query is scheduled. However unless the option is actively selected, queries will still not get scheduled.

**Option 2:**
- Create (once) a default DAG for queries e.g. `bqetl_default` and schedule it to run at a specific time.
- Add DAG `bqetl_default` as the [default DAG name to use in function schedule()](https://github.com/mozilla/bigquery-etl/blob/1c3ba13b4048d98d3da690b1a89710ab8c022f75/bigquery_etl/cli/query.py#LL259C1-L267C2).

- The [process to create a new query](https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#add-a-new-field-to-clients_daily) remains the same. However, users can run `bqetl query schedule ` without specifying a  DAG name and the process will schedule the query in the default DAG `bqetl_default`.

**Comment by scholtzan** [comment]
I think option 2 is a little more user-friendly since it doesn't require any additional parameters
