### ISSUE TITLE
Please help add org_mozilla_vrbrowser.clients_last_seen schema

### ISSUE THREAD

**Issue by daoshengmu** [mozilla/bigquery-etl#497]
Firefox Reality project have enabled Glean baseline pings, so we would like to have `org_mozilla_vrbrowser.clients_last_seen` to query our DAU/WAU/MAU. Please help add it. Thanks!

**Comment by jklukas** [comment]
This would be very similar logic to existing fenix clients_last_seen and clients_daily. There are, however, some fenix-specific metrics that are pulled in via the clients_daily query: https://github.com/mozilla/bigquery-etl/blob/master/templates/org_mozilla_fenix_derived/clients_daily_v1/query.sql#L62-L64

Are there are vrbrowser-specific metrics that you'd need to have pulled in for this? Or we could do just the info from baseline pings.

**Comment by daoshengmu** [comment]
I think there is only only specific metric we need for vrbrowser, `metrics.string.distribution_channel_name`.

**Comment by jklukas** [comment]
We're making some updates to how we do glean ETL in prep for Fenix launch, and I think we should pick up this org_mozilla_vrbrowser ETL while we're at it, so this should happen in coming weeks.

We'll basically want to duplicate `templates/org_mozilla_fenix_derived/clients_daily` and clients_last_seen, and modify to consider only the single `metrics.string.distribution_channel_name` metric. We also should change to use a LEFT JOIN from baseline pings to metrics pings rather than the union we currently use. Going forward, we should be considering a user active in a given day only if they sent a baseline ping. We do not want to count a user active based on a metrics ping alone.

**Comment by jklukas** [comment]
Once we have the clients_last_seen view set up, we can add that view into `telemetry.nondesktop_clients_last_seen`, which will get it flowing to the smoot_* tables that power GUD.

**Comment by scholtzan** [comment]
https://github.com/mozilla/bigquery-etl/pull/700 added `org_mozilla_vrbrowser.clients_last_seen`
