### ISSUE TITLE
Add an over-time comparison for telemetry missing columns  

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#644]
we currently have a dashboard [0], based on telemetry_missing_columns_v1, which shows us the top missing columns, but what we really need is to show how this has changed over time.

[0] https://sql.telemetry.mozilla.org/queries/65797/source#167094

**Comment by acmiyaguchi** [comment]
I took a quick look at this -- I think one I the reasons this wasn't added was due to the cost of the view. The full query scans over 1.1TB a day with a significant number of intermediate rows. The resulting dataset is only 65,273 rows for a single day.

The approach I would take would be to materialize the view (scheduled daily), and then write the queries on top of this. In this way, we would be able to look over all time in a fairly inexpensive way.

**Comment by acmiyaguchi** [comment]
I've added an analysis table using the `telemetry_live` dataset between 2019-12-01 and 2019-12-15 that took 4.9TB. It's available under `moz-fx-data-shared-prod:analysis.telemetry_missing_columns_nonprod_20191201_20191215`.

**Comment by acmiyaguchi** [comment]
The view in #658 is a bit easier to interpret. It might not do everything we want, but I think it provides a good start.
