### ISSUE TITLE
Add support for script.sql files

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#729]
The majority of this repo currently consists of `query.sql` files that define incremental queries are are executed with a destination table set. We also have some `init.sql` files that directly alter data without having a destination table set, issuing `CREATE TABLE ... AS` DDL statements.

I propose we support more complex ETL defined in SQL via `script.sql` files which would each contain a BigQuery [script](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting). We cannot specify a destination table when running a script, but we can run multiple data-changing commands, so we can achieve the same effect.

In particular, I am thinking of taking our main_summary definition, which currently consists of two separate queries that are joined together within a python script. We would instead define this as a `script.sql` where the last stages are a `DELETE FROM main_summary_v4 WHERE DATE(submission_timestamp) = @submission_date` and finally `SELECT * FROM my_temp_table INTO main_summary_v4`.

This has the benefit of  letting BigQuery handle all of the management of temporary tables and submission of intermediate query jobs. It has the disadvantage that the destination table name must be hard-coded into the `script.sql` job rather than being configurable.

I believe that `script.sql` could end up being a powerful primitive that allows more complex use cases; we could have a single script update multiple related tables, etc.

cc @relud @scholtzan

**Comment by relud** [comment]
> We would instead define [main_summary_v4] as a `script.sql` where the last stages are a `DELETE FROM main_summary_v4 WHERE DATE(submission_timestamp) = @submission_date` and finally `SELECT * FROM my_temp_table INTO main_summary_v4`

for `main_summary_v4` this would result in a few different undesirable behaviors:

- the `part1.sql` and `part2.sql` queries would run serially, instead of in parallel
- the `SELECT ... INTO` statement would be charged for scanning the data an extra time, unless we do the `JOIN` as part of the same query
- the `DELETE` statement would be charged for scanning the entire destination partition
- the `DELETE` statement would result in non-atomic updates, so during a backfill data would become unavailable for however long the `SELECT ... INTO` statement takes to run, which if it is also doing a `JOIN` could be a non-trivial amount of time.

> I believe that `script.sql` could end up being a powerful primitive that allows more complex use cases; we could have a single script update multiple related tables, etc.

I agree, and I'm definitely onboard for using `script.sql`, just not for `main_summary_v4` right now.

**Comment by jklukas** [comment]
@relud makes reasonable counterarguments for main_summary_v4, but I disagree on the following:

> the DELETE statement would result in non-atomic updates

It's my understanding that scripts essentially run as a single transaction. None of the effects of the script are visible until the entire script finishes.

**Comment by relud** [comment]
> It's my understanding that scripts essentially run as a single transaction. None of the effects of the script are visible until the entire script finishes.

whaaaat!? that's awesome!

**Comment by jklukas** [comment]
I now cannot find documentation to back up my understanding about transactions, so it may turn out that I'm wrong.

**Comment by jklukas** [comment]
I was indeed wrong. BQ scripts do not execute as transactions.

**Comment by ANich** [comment]
Support for `script.sql` was added here https://github.com/mozilla/bigquery-etl/pull/1323
